# Generated by Django 5.0.2 on 2025-10-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
